services:
  librechat:
    image: ghcr.io/danny-avila/librechat-dev:latest
    container_name: librechat
    restart: unless-stopped
    ports:
      - "3080:3080"
    env_file:
      - .env
    volumes:
      - ./librechat.yaml:/app/librechat.yaml:ro
      - ./sa-key.json:/app/sa-key.json:ro
      - librechat-images:/app/client/public/images
    depends_on:
      - mongodb
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/sa-key.json

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    command: mongod --wiredTigerCacheSizeGB 0.5 --quiet
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb-data:
  librechat-images:
